### ISSUE TITLE
throw error when status code 0

### ISSUE THREAD

**Issue by ming2020** [bojand/grpc-caller#40]
I call in try catch, and used Request API to show status code.
The status code is as follows, OK. 
```
Response {
  call:
   ClientUnaryCall {
     _events:
      [Object: null prototype] { metadata: [Function], status: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     call:
      InterceptingCall { next_call: [InterceptingCall], requester: undefined } },
  response: {},
  metadata: Metadata { _internal_repr: {} },
  status:
   { code: 0,
     details: '',
     metadata: Metadata { _internal_repr: {} } } }
```
But throw UNAVAILABLE ERROR. What a strange question.
```
{ Error: 14 UNAVAILABLE: Connect Failed
    at Object.exports.createStatusError (D:\ming2\Desktop\work\cawi-cloud\web-api-gateway\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (D:\ming2\Desktop\work\cawi-cloud\web-api-gateway\node_modules\grpc\src\client_interceptors.js:1204:28)
    at InterceptingListener._callNext (D:\ming2\Desktop\work\cawi-cloud\web-api-gateway\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (D:\ming2\Desktop\work\cawi-cloud\web-api-gateway\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (D:\ming2\Desktop\work\cawi-cloud\web-api-gateway\node_modules\grpc\src\client_interceptors.js:845:24)
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Connect Failed' }
```

**Comment by ming2020** [comment]
**grpc: 1.19.0
grpc-caller: 0.12.0**
